### ISSUE TITLE
请问 pbrpc 的 client 与 brpc 的 server 是否兼容？

### ISSUE THREAD

**Issue by choleraehyq** [baidu-golang/pbrpc#2]
目前 brpc 没有提供 Go 客户端支持，不过都支持 protobuf，如果选择 protobuf 作为序列化协议，能否直接使用 pbrpc 的客户端去连 brpc 的服务器？

**Comment by smbzhang** [comment]
看data.pb.go里的 rpc meta 数据和 baidu-rpc(c++)中的PROTOCOL_BAIDU_STD吻合（可能缺少Stream 功能）。应该是可以使用 pbrpc 的客户端去连 brpc 的服务器
